### PR TITLE
Replaced gap_df.append by pd.concat

### PR DESCRIPTION
**Pull request by psads-git**
Hi Miles,

I guess I am being successful with creating the pull request.

Thanks!

### CODE REVIEW

**Comment by milesgranger** [comment]
I'll take a closer look at this tomorrow, thanks! 👌

**Comment by psads-git** [comment]
Thanks, Miles!

**Comment by milesgranger** [comment]
Nice, looks like the failures are only related to formatting. [See the logs here](https://github.com/milesgranger/gap_statistic/actions/runs/3971420528/jobs/6808645670#step:5:134). Should be able to run [black](https://github.com/psf/black) on the offending file: `black gap_statistic/optimalK.py`.

**Comment by psads-git** [comment]
I have run `black` on `optimalK.py` and committed the new file, Miles. Thanks!

**Comment by milesgranger** [comment]
Excellent, seems though maybe the black you have is [different from the one CI is using](https://github.com/milesgranger/gap_statistic/actions/runs/3974285871/jobs/6813516583#step:5:33) so it still thinks it's formatted wrong. Seems if you do `pip install black==23.1a1` that may fix it. 

I guess it'd be better too if I took the time to pin the [black dependency](https://github.com/milesgranger/gap_statistic/blob/988b80dca52f611864d22e25db96fc3b3376c4a7/setup.py#L13)

**Comment by psads-git** [comment]
Thanks, Miles. Should I wait until you pin the dependency or should I try with the `black` version you suggest?

**Comment by milesgranger** [comment]
Ya, if you can just install that specific version and retry, we'll verify it works. :)

**Comment by psads-git** [comment]
Done so, Miles.

**Review by milesgranger — APPROVED** [review]
Fantastic, thank you!

(And congratulations on your first PR! :tada: )

**Comment by psads-git** [comment]
Thanks for your help, Miles. 

Will the new version of `gap-statistic` be available to install from `pip` right away? Or does the process take time?

**Comment by milesgranger** [comment]
Ya, I can do that soon. :+1:

**Comment by psads-git** [comment]
Great, Miles! Have a nice weekend!

**Comment by milesgranger** [comment]
Done [PyPI v2.02](https://pypi.org/project/gap-stat/2.0.2/)
Thanks, same to you. :)

**Pull request merged**
